### ISSUE TITLE
Incorrect snpEff path and package in Linux install. Error on step: rMAP is will now perform Annotation of Variants

### ISSUE THREAD

**Issue by jpcartailler** [GunzIvan28/rMAP#11]
Greetings,

We found this issue in Linux install:
```
rMAP is will now perform Annotation of Variants...
chmod: cannot access '/home/user/miniconda3/envs/rMAP-1.0/share/snpeff-4.5covid19-1/snpEff.jar': No such file or directory
chmod: cannot access '/home/user/miniconda3/envs/rMAP-1.0/share/snpeff-4.5covid19-1/*': No such file or directory
```

There's two things wrong with the above:

1. Our conda envs aren't installed in `/home/$USER`, then are installed elsewhere. I guess we can create symlinks for now, but it would be better for rMAP to use `$CONDA_PREFIX` - I'm not sure how feasible that is for you to do, but certainly easy for me to suggest :)
2. Our install doesn't have `snpeff-4.5covid19-1`, we have `snpeff-5.0-1`. What is the best to work around this?

Thanks!

**Comment by GunzIvan28** [comment]
@c5creative,

Thanks for using the rMAP tool. We would suggest the following tips as workarounds for the issues you are experiencing:

1. Since you are using a HPC, we assume most of the softwares were already pre-installed by the systems admin and may have varying versions from the packages that are used by rMAP. In that case, we advise you follow the installation instructions and compile the rMAP toolbox within its own environment with its own packages and dependencies to avoid conflicts with the snpeff tool present on your resident HPC.

2. The "CONDA_PREFIX" is the right way to go and if you can find where to insert it within the file, it would be great. We had a user who had suggested that before sometime back within the issues as a way of catering for people who maybe running anaconda but we as the developers have not yet tested and found time to incorporate it yet as we are still fixed sorting some other issues. But we are going to put this into consideration and resolve it with the utmost urgency as soon as possible.

3. At the moment, there is no way of skipping already finished computations within the pipeline except if I walk you through specific lines to hash/comment out. On the brighter side, we are implementing the pipeline within the nextflow engine which we will launch as version 2 to cater for the resume option and compatibility with HPC clusters. 

Try this out and let me know how it goes. In case you need to run specific steps without resuming the whole run, I could share my mail and we possibly have a zoom where I can walk you through which parts to shut off in the main script.


Cheers,
Ivan

**Comment by jpcartailler** [comment]
Hi Ivan,

Thanks for the very fast response!

1. I installed rMAP on our HPC within our group environment in its own conda environment and was done so according to the installation procedure (rMAP-1.0-Linux-installer.yml, then setup.sh...). The rMAP installer installed: `/private/conda/envs/rMAP-1.0/share/snpeff-5.0-1`, *not* `share/snpeff-4.5covid19-1/`. Our cluster does not have any version of snpeff on path.

    And the `rMAP-1.0-Linux-installer.yml` requires `snpeff=5.0`... so I'm really unclear as to how the "Annotation of Variants" step is looking for `share/snpeff-4.5covid19-1/`. After another look, it appears that `snpeff-4.5covid19-1` is a requirement for the `rMAP-1.0-MacOs-installer.yml` version.

2. Thank you, happy to help beta-test...

3. Great! Would welcome a Nextflow version!
`

**Comment by jpcartailler** [comment]
Found the issue- the rMAP shell script directly references the `snpeff-4.5covid19-1`:

https://github.com/GunzIvan28/rMAP/blob/b22bbd2bbe2c740b67fcd7696d15d9a93264f04c/bin/rMAP#L524-L526

**Comment by GunzIvan28** [comment]
@c5creative,
I have updated the main script with the version for `snpeff-5.0-1` as picked by the .yml installer file. I have tested it and the annotation ran successfully. 

Just for reference, update the lines in the main script as follows:
```
562 chmod 777 $HOME/miniconda3/envs/rMAP-1.0/share/snpeff-5.0-1/snpEff.jar
563 chmod 777 $HOME/miniconda3/envs/rMAP-1.0/share/snpeff-5.0-1/*
564  SNPEFF="$HOME/miniconda3/envs/rMAP-1.0/share/snpeff-5.0-1"
```

**Comment by GunzIvan28** [comment]
Thanks @c5creative for this input. We are implementing the changes as advised
